/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the MxedgeVersions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MxedgeVersions{}

// MxedgeVersions struct for MxedgeVersions
type MxedgeVersions struct {
	Mxagent *string `json:"mxagent,omitempty"`
	Tuntnerm *string `json:"tuntnerm,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MxedgeVersions MxedgeVersions

// NewMxedgeVersions instantiates a new MxedgeVersions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMxedgeVersions() *MxedgeVersions {
	this := MxedgeVersions{}
	return &this
}

// NewMxedgeVersionsWithDefaults instantiates a new MxedgeVersions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMxedgeVersionsWithDefaults() *MxedgeVersions {
	this := MxedgeVersions{}
	return &this
}

// GetMxagent returns the Mxagent field value if set, zero value otherwise.
func (o *MxedgeVersions) GetMxagent() string {
	if o == nil || IsNil(o.Mxagent) {
		var ret string
		return ret
	}
	return *o.Mxagent
}

// GetMxagentOk returns a tuple with the Mxagent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MxedgeVersions) GetMxagentOk() (*string, bool) {
	if o == nil || IsNil(o.Mxagent) {
		return nil, false
	}
	return o.Mxagent, true
}

// HasMxagent returns a boolean if a field has been set.
func (o *MxedgeVersions) HasMxagent() bool {
	if o != nil && !IsNil(o.Mxagent) {
		return true
	}

	return false
}

// SetMxagent gets a reference to the given string and assigns it to the Mxagent field.
func (o *MxedgeVersions) SetMxagent(v string) {
	o.Mxagent = &v
}

// GetTuntnerm returns the Tuntnerm field value if set, zero value otherwise.
func (o *MxedgeVersions) GetTuntnerm() string {
	if o == nil || IsNil(o.Tuntnerm) {
		var ret string
		return ret
	}
	return *o.Tuntnerm
}

// GetTuntnermOk returns a tuple with the Tuntnerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MxedgeVersions) GetTuntnermOk() (*string, bool) {
	if o == nil || IsNil(o.Tuntnerm) {
		return nil, false
	}
	return o.Tuntnerm, true
}

// HasTuntnerm returns a boolean if a field has been set.
func (o *MxedgeVersions) HasTuntnerm() bool {
	if o != nil && !IsNil(o.Tuntnerm) {
		return true
	}

	return false
}

// SetTuntnerm gets a reference to the given string and assigns it to the Tuntnerm field.
func (o *MxedgeVersions) SetTuntnerm(v string) {
	o.Tuntnerm = &v
}

func (o MxedgeVersions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MxedgeVersions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mxagent) {
		toSerialize["mxagent"] = o.Mxagent
	}
	if !IsNil(o.Tuntnerm) {
		toSerialize["tuntnerm"] = o.Tuntnerm
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MxedgeVersions) UnmarshalJSON(data []byte) (err error) {
	varMxedgeVersions := _MxedgeVersions{}

	err = json.Unmarshal(data, &varMxedgeVersions)

	if err != nil {
		return err
	}

	*o = MxedgeVersions(varMxedgeVersions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mxagent")
		delete(additionalProperties, "tuntnerm")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMxedgeVersions struct {
	value *MxedgeVersions
	isSet bool
}

func (v NullableMxedgeVersions) Get() *MxedgeVersions {
	return v.value
}

func (v *NullableMxedgeVersions) Set(val *MxedgeVersions) {
	v.value = val
	v.isSet = true
}

func (v NullableMxedgeVersions) IsSet() bool {
	return v.isSet
}

func (v *NullableMxedgeVersions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMxedgeVersions(val *MxedgeVersions) *NullableMxedgeVersions {
	return &NullableMxedgeVersions{value: val, isSet: true}
}

func (v NullableMxedgeVersions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMxedgeVersions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


