/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the MxedgeDas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MxedgeDas{}

// MxedgeDas configure cloud-assisted dynamic authorization service on this cluster of mist edges
type MxedgeDas struct {
	// dynamic authorization clients configured to send CoA|DM to mist edges on port 3799
	CoaServers []MxedgeDasCoaServer `json:"coa_servers,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MxedgeDas MxedgeDas

// NewMxedgeDas instantiates a new MxedgeDas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMxedgeDas() *MxedgeDas {
	this := MxedgeDas{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewMxedgeDasWithDefaults instantiates a new MxedgeDas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMxedgeDasWithDefaults() *MxedgeDas {
	this := MxedgeDas{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetCoaServers returns the CoaServers field value if set, zero value otherwise.
func (o *MxedgeDas) GetCoaServers() []MxedgeDasCoaServer {
	if o == nil || IsNil(o.CoaServers) {
		var ret []MxedgeDasCoaServer
		return ret
	}
	return o.CoaServers
}

// GetCoaServersOk returns a tuple with the CoaServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MxedgeDas) GetCoaServersOk() ([]MxedgeDasCoaServer, bool) {
	if o == nil || IsNil(o.CoaServers) {
		return nil, false
	}
	return o.CoaServers, true
}

// HasCoaServers returns a boolean if a field has been set.
func (o *MxedgeDas) HasCoaServers() bool {
	if o != nil && !IsNil(o.CoaServers) {
		return true
	}

	return false
}

// SetCoaServers gets a reference to the given []MxedgeDasCoaServer and assigns it to the CoaServers field.
func (o *MxedgeDas) SetCoaServers(v []MxedgeDasCoaServer) {
	o.CoaServers = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *MxedgeDas) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MxedgeDas) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *MxedgeDas) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *MxedgeDas) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o MxedgeDas) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MxedgeDas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CoaServers) {
		toSerialize["coa_servers"] = o.CoaServers
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MxedgeDas) UnmarshalJSON(data []byte) (err error) {
	varMxedgeDas := _MxedgeDas{}

	err = json.Unmarshal(data, &varMxedgeDas)

	if err != nil {
		return err
	}

	*o = MxedgeDas(varMxedgeDas)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "coa_servers")
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMxedgeDas struct {
	value *MxedgeDas
	isSet bool
}

func (v NullableMxedgeDas) Get() *MxedgeDas {
	return v.value
}

func (v *NullableMxedgeDas) Set(val *MxedgeDas) {
	v.value = val
	v.isSet = true
}

func (v NullableMxedgeDas) IsSet() bool {
	return v.isSet
}

func (v *NullableMxedgeDas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMxedgeDas(val *MxedgeDas) *NullableMxedgeDas {
	return &NullableMxedgeDas{value: val, isSet: true}
}

func (v NullableMxedgeDas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMxedgeDas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


