/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the WebhookDelivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDelivery{}

// WebhookDelivery struct for WebhookDelivery
type WebhookDelivery struct {
	// error message, if there is one
	Error *string `json:"error,omitempty"`
	// delivery ID
	Id *string `json:"id,omitempty"`
	OrgId *string `json:"org_id,omitempty"`
	// HTTP request headers
	ReqHeaders *string `json:"req_headers,omitempty"`
	// HTTP request payload
	ReqPayload *string `json:"req_payload,omitempty"`
	// HTTP request URL
	ReqUrl *string `json:"req_url,omitempty"`
	// HTTP response body
	RespBody *string `json:"resp_body,omitempty"`
	// HTTP response headers
	RespHeaders *string `json:"resp_headers,omitempty"`
	SiteId *string `json:"site_id,omitempty"`
	Status *WebhookDeliveryStatus `json:"status,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
	Topic *WebhookDeliveryTopic `json:"topic,omitempty"`
	WebhookId *string `json:"webhook_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebhookDelivery WebhookDelivery

// NewWebhookDelivery instantiates a new WebhookDelivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDelivery() *WebhookDelivery {
	this := WebhookDelivery{}
	return &this
}

// NewWebhookDeliveryWithDefaults instantiates a new WebhookDelivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryWithDefaults() *WebhookDelivery {
	this := WebhookDelivery{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WebhookDelivery) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WebhookDelivery) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *WebhookDelivery) SetError(v string) {
	o.Error = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebhookDelivery) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebhookDelivery) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WebhookDelivery) SetId(v string) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *WebhookDelivery) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *WebhookDelivery) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *WebhookDelivery) SetOrgId(v string) {
	o.OrgId = &v
}

// GetReqHeaders returns the ReqHeaders field value if set, zero value otherwise.
func (o *WebhookDelivery) GetReqHeaders() string {
	if o == nil || IsNil(o.ReqHeaders) {
		var ret string
		return ret
	}
	return *o.ReqHeaders
}

// GetReqHeadersOk returns a tuple with the ReqHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetReqHeadersOk() (*string, bool) {
	if o == nil || IsNil(o.ReqHeaders) {
		return nil, false
	}
	return o.ReqHeaders, true
}

// HasReqHeaders returns a boolean if a field has been set.
func (o *WebhookDelivery) HasReqHeaders() bool {
	if o != nil && !IsNil(o.ReqHeaders) {
		return true
	}

	return false
}

// SetReqHeaders gets a reference to the given string and assigns it to the ReqHeaders field.
func (o *WebhookDelivery) SetReqHeaders(v string) {
	o.ReqHeaders = &v
}

// GetReqPayload returns the ReqPayload field value if set, zero value otherwise.
func (o *WebhookDelivery) GetReqPayload() string {
	if o == nil || IsNil(o.ReqPayload) {
		var ret string
		return ret
	}
	return *o.ReqPayload
}

// GetReqPayloadOk returns a tuple with the ReqPayload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetReqPayloadOk() (*string, bool) {
	if o == nil || IsNil(o.ReqPayload) {
		return nil, false
	}
	return o.ReqPayload, true
}

// HasReqPayload returns a boolean if a field has been set.
func (o *WebhookDelivery) HasReqPayload() bool {
	if o != nil && !IsNil(o.ReqPayload) {
		return true
	}

	return false
}

// SetReqPayload gets a reference to the given string and assigns it to the ReqPayload field.
func (o *WebhookDelivery) SetReqPayload(v string) {
	o.ReqPayload = &v
}

// GetReqUrl returns the ReqUrl field value if set, zero value otherwise.
func (o *WebhookDelivery) GetReqUrl() string {
	if o == nil || IsNil(o.ReqUrl) {
		var ret string
		return ret
	}
	return *o.ReqUrl
}

// GetReqUrlOk returns a tuple with the ReqUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetReqUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReqUrl) {
		return nil, false
	}
	return o.ReqUrl, true
}

// HasReqUrl returns a boolean if a field has been set.
func (o *WebhookDelivery) HasReqUrl() bool {
	if o != nil && !IsNil(o.ReqUrl) {
		return true
	}

	return false
}

// SetReqUrl gets a reference to the given string and assigns it to the ReqUrl field.
func (o *WebhookDelivery) SetReqUrl(v string) {
	o.ReqUrl = &v
}

// GetRespBody returns the RespBody field value if set, zero value otherwise.
func (o *WebhookDelivery) GetRespBody() string {
	if o == nil || IsNil(o.RespBody) {
		var ret string
		return ret
	}
	return *o.RespBody
}

// GetRespBodyOk returns a tuple with the RespBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetRespBodyOk() (*string, bool) {
	if o == nil || IsNil(o.RespBody) {
		return nil, false
	}
	return o.RespBody, true
}

// HasRespBody returns a boolean if a field has been set.
func (o *WebhookDelivery) HasRespBody() bool {
	if o != nil && !IsNil(o.RespBody) {
		return true
	}

	return false
}

// SetRespBody gets a reference to the given string and assigns it to the RespBody field.
func (o *WebhookDelivery) SetRespBody(v string) {
	o.RespBody = &v
}

// GetRespHeaders returns the RespHeaders field value if set, zero value otherwise.
func (o *WebhookDelivery) GetRespHeaders() string {
	if o == nil || IsNil(o.RespHeaders) {
		var ret string
		return ret
	}
	return *o.RespHeaders
}

// GetRespHeadersOk returns a tuple with the RespHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetRespHeadersOk() (*string, bool) {
	if o == nil || IsNil(o.RespHeaders) {
		return nil, false
	}
	return o.RespHeaders, true
}

// HasRespHeaders returns a boolean if a field has been set.
func (o *WebhookDelivery) HasRespHeaders() bool {
	if o != nil && !IsNil(o.RespHeaders) {
		return true
	}

	return false
}

// SetRespHeaders gets a reference to the given string and assigns it to the RespHeaders field.
func (o *WebhookDelivery) SetRespHeaders(v string) {
	o.RespHeaders = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *WebhookDelivery) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *WebhookDelivery) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *WebhookDelivery) SetSiteId(v string) {
	o.SiteId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WebhookDelivery) GetStatus() WebhookDeliveryStatus {
	if o == nil || IsNil(o.Status) {
		var ret WebhookDeliveryStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetStatusOk() (*WebhookDeliveryStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WebhookDelivery) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given WebhookDeliveryStatus and assigns it to the Status field.
func (o *WebhookDelivery) SetStatus(v WebhookDeliveryStatus) {
	o.Status = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *WebhookDelivery) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *WebhookDelivery) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *WebhookDelivery) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *WebhookDelivery) GetTimestamp() float32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret float32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetTimestampOk() (*float32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *WebhookDelivery) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given float32 and assigns it to the Timestamp field.
func (o *WebhookDelivery) SetTimestamp(v float32) {
	o.Timestamp = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *WebhookDelivery) GetTopic() WebhookDeliveryTopic {
	if o == nil || IsNil(o.Topic) {
		var ret WebhookDeliveryTopic
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetTopicOk() (*WebhookDeliveryTopic, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *WebhookDelivery) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given WebhookDeliveryTopic and assigns it to the Topic field.
func (o *WebhookDelivery) SetTopic(v WebhookDeliveryTopic) {
	o.Topic = &v
}

// GetWebhookId returns the WebhookId field value if set, zero value otherwise.
func (o *WebhookDelivery) GetWebhookId() string {
	if o == nil || IsNil(o.WebhookId) {
		var ret string
		return ret
	}
	return *o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDelivery) GetWebhookIdOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookId) {
		return nil, false
	}
	return o.WebhookId, true
}

// HasWebhookId returns a boolean if a field has been set.
func (o *WebhookDelivery) HasWebhookId() bool {
	if o != nil && !IsNil(o.WebhookId) {
		return true
	}

	return false
}

// SetWebhookId gets a reference to the given string and assigns it to the WebhookId field.
func (o *WebhookDelivery) SetWebhookId(v string) {
	o.WebhookId = &v
}

func (o WebhookDelivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDelivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.ReqHeaders) {
		toSerialize["req_headers"] = o.ReqHeaders
	}
	if !IsNil(o.ReqPayload) {
		toSerialize["req_payload"] = o.ReqPayload
	}
	if !IsNil(o.ReqUrl) {
		toSerialize["req_url"] = o.ReqUrl
	}
	if !IsNil(o.RespBody) {
		toSerialize["resp_body"] = o.RespBody
	}
	if !IsNil(o.RespHeaders) {
		toSerialize["resp_headers"] = o.RespHeaders
	}
	if !IsNil(o.SiteId) {
		toSerialize["site_id"] = o.SiteId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	if !IsNil(o.WebhookId) {
		toSerialize["webhook_id"] = o.WebhookId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookDelivery) UnmarshalJSON(data []byte) (err error) {
	varWebhookDelivery := _WebhookDelivery{}

	err = json.Unmarshal(data, &varWebhookDelivery)

	if err != nil {
		return err
	}

	*o = WebhookDelivery(varWebhookDelivery)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "id")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "req_headers")
		delete(additionalProperties, "req_payload")
		delete(additionalProperties, "req_url")
		delete(additionalProperties, "resp_body")
		delete(additionalProperties, "resp_headers")
		delete(additionalProperties, "site_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "status_code")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "topic")
		delete(additionalProperties, "webhook_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookDelivery struct {
	value *WebhookDelivery
	isSet bool
}

func (v NullableWebhookDelivery) Get() *WebhookDelivery {
	return v.value
}

func (v *NullableWebhookDelivery) Set(val *WebhookDelivery) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDelivery(val *WebhookDelivery) *NullableWebhookDelivery {
	return &NullableWebhookDelivery{value: val, isSet: true}
}

func (v NullableWebhookDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


