/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// TacacsDefaultRole the model 'TacacsDefaultRole'
type TacacsDefaultRole string

// List of tacacs_default_role
const (
	TACACSDEFAULTROLE_EMPTY TacacsDefaultRole = ""
	TACACSDEFAULTROLE_ADMIN TacacsDefaultRole = "admin"
	TACACSDEFAULTROLE_NONE TacacsDefaultRole = "none"
	TACACSDEFAULTROLE_READ TacacsDefaultRole = "read"
	TACACSDEFAULTROLE_HELPDESK TacacsDefaultRole = "helpdesk"
)

// All allowed values of TacacsDefaultRole enum
var AllowedTacacsDefaultRoleEnumValues = []TacacsDefaultRole{
	"",
	"admin",
	"none",
	"read",
	"helpdesk",
}

func (v *TacacsDefaultRole) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TacacsDefaultRole(value)
	for _, existing := range AllowedTacacsDefaultRoleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TacacsDefaultRole", value)
}

// NewTacacsDefaultRoleFromValue returns a pointer to a valid TacacsDefaultRole
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTacacsDefaultRoleFromValue(v string) (*TacacsDefaultRole, error) {
	ev := TacacsDefaultRole(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TacacsDefaultRole: valid values are %v", v, AllowedTacacsDefaultRoleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TacacsDefaultRole) IsValid() bool {
	for _, existing := range AllowedTacacsDefaultRoleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to tacacs_default_role value
func (v TacacsDefaultRole) Ptr() *TacacsDefaultRole {
	return &v
}

type NullableTacacsDefaultRole struct {
	value *TacacsDefaultRole
	isSet bool
}

func (v NullableTacacsDefaultRole) Get() *TacacsDefaultRole {
	return v.value
}

func (v *NullableTacacsDefaultRole) Set(val *TacacsDefaultRole) {
	v.value = val
	v.isSet = true
}

func (v NullableTacacsDefaultRole) IsSet() bool {
	return v.isSet
}

func (v *NullableTacacsDefaultRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTacacsDefaultRole(val *TacacsDefaultRole) *NullableTacacsDefaultRole {
	return &NullableTacacsDefaultRole{value: val, isSet: true}
}

func (v NullableTacacsDefaultRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTacacsDefaultRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

