/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigVcPortMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigVcPortMember{}

// ConfigVcPortMember struct for ConfigVcPortMember
type ConfigVcPortMember struct {
	Member float32 `json:"member"`
	VcPorts []string `json:"vc_ports,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigVcPortMember ConfigVcPortMember

// NewConfigVcPortMember instantiates a new ConfigVcPortMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigVcPortMember(member float32) *ConfigVcPortMember {
	this := ConfigVcPortMember{}
	this.Member = member
	return &this
}

// NewConfigVcPortMemberWithDefaults instantiates a new ConfigVcPortMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigVcPortMemberWithDefaults() *ConfigVcPortMember {
	this := ConfigVcPortMember{}
	return &this
}

// GetMember returns the Member field value
func (o *ConfigVcPortMember) GetMember() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Member
}

// GetMemberOk returns a tuple with the Member field value
// and a boolean to check if the value has been set.
func (o *ConfigVcPortMember) GetMemberOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Member, true
}

// SetMember sets field value
func (o *ConfigVcPortMember) SetMember(v float32) {
	o.Member = v
}

// GetVcPorts returns the VcPorts field value if set, zero value otherwise.
func (o *ConfigVcPortMember) GetVcPorts() []string {
	if o == nil || IsNil(o.VcPorts) {
		var ret []string
		return ret
	}
	return o.VcPorts
}

// GetVcPortsOk returns a tuple with the VcPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigVcPortMember) GetVcPortsOk() ([]string, bool) {
	if o == nil || IsNil(o.VcPorts) {
		return nil, false
	}
	return o.VcPorts, true
}

// HasVcPorts returns a boolean if a field has been set.
func (o *ConfigVcPortMember) HasVcPorts() bool {
	if o != nil && !IsNil(o.VcPorts) {
		return true
	}

	return false
}

// SetVcPorts gets a reference to the given []string and assigns it to the VcPorts field.
func (o *ConfigVcPortMember) SetVcPorts(v []string) {
	o.VcPorts = v
}

func (o ConfigVcPortMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigVcPortMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["member"] = o.Member
	if !IsNil(o.VcPorts) {
		toSerialize["vc_ports"] = o.VcPorts
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigVcPortMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"member",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigVcPortMember := _ConfigVcPortMember{}

	err = json.Unmarshal(data, &varConfigVcPortMember)

	if err != nil {
		return err
	}

	*o = ConfigVcPortMember(varConfigVcPortMember)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "member")
		delete(additionalProperties, "vc_ports")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigVcPortMember struct {
	value *ConfigVcPortMember
	isSet bool
}

func (v NullableConfigVcPortMember) Get() *ConfigVcPortMember {
	return v.value
}

func (v *NullableConfigVcPortMember) Set(val *ConfigVcPortMember) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigVcPortMember) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigVcPortMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigVcPortMember(val *ConfigVcPortMember) *NullableConfigVcPortMember {
	return &NullableConfigVcPortMember{value: val, isSet: true}
}

func (v NullableConfigVcPortMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigVcPortMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


