/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// IdpProfileMatchingSeverityValue the model 'IdpProfileMatchingSeverityValue'
type IdpProfileMatchingSeverityValue string

// List of idp_profile_matching_severity_value
const (
	IDPPROFILEMATCHINGSEVERITYVALUE_EMPTY IdpProfileMatchingSeverityValue = ""
	IDPPROFILEMATCHINGSEVERITYVALUE_CRITICAL IdpProfileMatchingSeverityValue = "critical"
	IDPPROFILEMATCHINGSEVERITYVALUE_MAJOR IdpProfileMatchingSeverityValue = "major"
	IDPPROFILEMATCHINGSEVERITYVALUE_MINOR IdpProfileMatchingSeverityValue = "minor"
	IDPPROFILEMATCHINGSEVERITYVALUE_INFO IdpProfileMatchingSeverityValue = "info"
)

// All allowed values of IdpProfileMatchingSeverityValue enum
var AllowedIdpProfileMatchingSeverityValueEnumValues = []IdpProfileMatchingSeverityValue{
	"",
	"critical",
	"major",
	"minor",
	"info",
}

func (v *IdpProfileMatchingSeverityValue) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IdpProfileMatchingSeverityValue(value)
	for _, existing := range AllowedIdpProfileMatchingSeverityValueEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IdpProfileMatchingSeverityValue", value)
}

// NewIdpProfileMatchingSeverityValueFromValue returns a pointer to a valid IdpProfileMatchingSeverityValue
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIdpProfileMatchingSeverityValueFromValue(v string) (*IdpProfileMatchingSeverityValue, error) {
	ev := IdpProfileMatchingSeverityValue(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IdpProfileMatchingSeverityValue: valid values are %v", v, AllowedIdpProfileMatchingSeverityValueEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IdpProfileMatchingSeverityValue) IsValid() bool {
	for _, existing := range AllowedIdpProfileMatchingSeverityValueEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to idp_profile_matching_severity_value value
func (v IdpProfileMatchingSeverityValue) Ptr() *IdpProfileMatchingSeverityValue {
	return &v
}

type NullableIdpProfileMatchingSeverityValue struct {
	value *IdpProfileMatchingSeverityValue
	isSet bool
}

func (v NullableIdpProfileMatchingSeverityValue) Get() *IdpProfileMatchingSeverityValue {
	return v.value
}

func (v *NullableIdpProfileMatchingSeverityValue) Set(val *IdpProfileMatchingSeverityValue) {
	v.value = val
	v.isSet = true
}

func (v NullableIdpProfileMatchingSeverityValue) IsSet() bool {
	return v.isSet
}

func (v *NullableIdpProfileMatchingSeverityValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdpProfileMatchingSeverityValue(val *IdpProfileMatchingSeverityValue) *NullableIdpProfileMatchingSeverityValue {
	return &NullableIdpProfileMatchingSeverityValue{value: val, isSet: true}
}

func (v NullableIdpProfileMatchingSeverityValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdpProfileMatchingSeverityValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

