/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the SiteSettingConfigPushPolicyPushWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteSettingConfigPushPolicyPushWindow{}

// SiteSettingConfigPushPolicyPushWindow if enabled, new config will only be pushed to device within the specified time window
type SiteSettingConfigPushPolicyPushWindow struct {
	Enabled *bool `json:"enabled,omitempty"`
	Hours *Hours `json:"hours,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SiteSettingConfigPushPolicyPushWindow SiteSettingConfigPushPolicyPushWindow

// NewSiteSettingConfigPushPolicyPushWindow instantiates a new SiteSettingConfigPushPolicyPushWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteSettingConfigPushPolicyPushWindow() *SiteSettingConfigPushPolicyPushWindow {
	this := SiteSettingConfigPushPolicyPushWindow{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewSiteSettingConfigPushPolicyPushWindowWithDefaults instantiates a new SiteSettingConfigPushPolicyPushWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteSettingConfigPushPolicyPushWindowWithDefaults() *SiteSettingConfigPushPolicyPushWindow {
	this := SiteSettingConfigPushPolicyPushWindow{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *SiteSettingConfigPushPolicyPushWindow) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteSettingConfigPushPolicyPushWindow) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *SiteSettingConfigPushPolicyPushWindow) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *SiteSettingConfigPushPolicyPushWindow) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetHours returns the Hours field value if set, zero value otherwise.
func (o *SiteSettingConfigPushPolicyPushWindow) GetHours() Hours {
	if o == nil || IsNil(o.Hours) {
		var ret Hours
		return ret
	}
	return *o.Hours
}

// GetHoursOk returns a tuple with the Hours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteSettingConfigPushPolicyPushWindow) GetHoursOk() (*Hours, bool) {
	if o == nil || IsNil(o.Hours) {
		return nil, false
	}
	return o.Hours, true
}

// HasHours returns a boolean if a field has been set.
func (o *SiteSettingConfigPushPolicyPushWindow) HasHours() bool {
	if o != nil && !IsNil(o.Hours) {
		return true
	}

	return false
}

// SetHours gets a reference to the given Hours and assigns it to the Hours field.
func (o *SiteSettingConfigPushPolicyPushWindow) SetHours(v Hours) {
	o.Hours = &v
}

func (o SiteSettingConfigPushPolicyPushWindow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteSettingConfigPushPolicyPushWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Hours) {
		toSerialize["hours"] = o.Hours
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SiteSettingConfigPushPolicyPushWindow) UnmarshalJSON(data []byte) (err error) {
	varSiteSettingConfigPushPolicyPushWindow := _SiteSettingConfigPushPolicyPushWindow{}

	err = json.Unmarshal(data, &varSiteSettingConfigPushPolicyPushWindow)

	if err != nil {
		return err
	}

	*o = SiteSettingConfigPushPolicyPushWindow(varSiteSettingConfigPushPolicyPushWindow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "hours")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSiteSettingConfigPushPolicyPushWindow struct {
	value *SiteSettingConfigPushPolicyPushWindow
	isSet bool
}

func (v NullableSiteSettingConfigPushPolicyPushWindow) Get() *SiteSettingConfigPushPolicyPushWindow {
	return v.value
}

func (v *NullableSiteSettingConfigPushPolicyPushWindow) Set(val *SiteSettingConfigPushPolicyPushWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteSettingConfigPushPolicyPushWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteSettingConfigPushPolicyPushWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteSettingConfigPushPolicyPushWindow(val *SiteSettingConfigPushPolicyPushWindow) *NullableSiteSettingConfigPushPolicyPushWindow {
	return &NullableSiteSettingConfigPushPolicyPushWindow{value: val, isSet: true}
}

func (v NullableSiteSettingConfigPushPolicyPushWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteSettingConfigPushPolicyPushWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


