/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// OrgWanClientsCountDistinct the model 'OrgWanClientsCountDistinct'
type OrgWanClientsCountDistinct string

// List of org_wan_clients_count_distinct
const (
	ORGWANCLIENTSCOUNTDISTINCT_EMPTY OrgWanClientsCountDistinct = ""
	ORGWANCLIENTSCOUNTDISTINCT_HOSTNAME OrgWanClientsCountDistinct = "hostname"
	ORGWANCLIENTSCOUNTDISTINCT_IP OrgWanClientsCountDistinct = "ip"
	ORGWANCLIENTSCOUNTDISTINCT_MFG OrgWanClientsCountDistinct = "mfg"
	ORGWANCLIENTSCOUNTDISTINCT_MAC OrgWanClientsCountDistinct = "mac"
)

// All allowed values of OrgWanClientsCountDistinct enum
var AllowedOrgWanClientsCountDistinctEnumValues = []OrgWanClientsCountDistinct{
	"",
	"hostname",
	"ip",
	"mfg",
	"mac",
}

func (v *OrgWanClientsCountDistinct) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrgWanClientsCountDistinct(value)
	for _, existing := range AllowedOrgWanClientsCountDistinctEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrgWanClientsCountDistinct", value)
}

// NewOrgWanClientsCountDistinctFromValue returns a pointer to a valid OrgWanClientsCountDistinct
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrgWanClientsCountDistinctFromValue(v string) (*OrgWanClientsCountDistinct, error) {
	ev := OrgWanClientsCountDistinct(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrgWanClientsCountDistinct: valid values are %v", v, AllowedOrgWanClientsCountDistinctEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrgWanClientsCountDistinct) IsValid() bool {
	for _, existing := range AllowedOrgWanClientsCountDistinctEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to org_wan_clients_count_distinct value
func (v OrgWanClientsCountDistinct) Ptr() *OrgWanClientsCountDistinct {
	return &v
}

type NullableOrgWanClientsCountDistinct struct {
	value *OrgWanClientsCountDistinct
	isSet bool
}

func (v NullableOrgWanClientsCountDistinct) Get() *OrgWanClientsCountDistinct {
	return v.value
}

func (v *NullableOrgWanClientsCountDistinct) Set(val *OrgWanClientsCountDistinct) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgWanClientsCountDistinct) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgWanClientsCountDistinct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgWanClientsCountDistinct(val *OrgWanClientsCountDistinct) *NullableOrgWanClientsCountDistinct {
	return &NullableOrgWanClientsCountDistinct{value: val, isSet: true}
}

func (v NullableOrgWanClientsCountDistinct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgWanClientsCountDistinct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

