/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the StatsSite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsSite{}

// StatsSite Site statistics
type StatsSite struct {
	Address string `json:"address"`
	AlarmtemplateId string `json:"alarmtemplate_id"`
	CountryCode string `json:"country_code"`
	CreatedTime float32 `json:"created_time"`
	Id string `json:"id"`
	Lat float32 `json:"lat"`
	Latlng LatLng `json:"latlng"`
	Lng float32 `json:"lng"`
	ModifiedTime float32 `json:"modified_time"`
	MspId string `json:"msp_id"`
	Name string `json:"name"`
	NetworktemplateId string `json:"networktemplate_id"`
	NumAp int32 `json:"num_ap"`
	NumApConnected int32 `json:"num_ap_connected"`
	NumClients int32 `json:"num_clients"`
	NumDevices int32 `json:"num_devices"`
	NumDevicesConnected int32 `json:"num_devices_connected"`
	NumGateway int32 `json:"num_gateway"`
	NumGatewayConnected int32 `json:"num_gateway_connected"`
	NumSwitch int32 `json:"num_switch"`
	NumSwitchConnected int32 `json:"num_switch_connected"`
	OrgId string `json:"org_id"`
	RftemplateId string `json:"rftemplate_id"`
	SecpolicyId interface{} `json:"secpolicy_id,omitempty"`
	SitegroupIds []string `json:"sitegroup_ids"`
	Timezone string `json:"timezone"`
	Tzoffset int32 `json:"tzoffset"`
	AdditionalProperties map[string]interface{}
}

type _StatsSite StatsSite

// NewStatsSite instantiates a new StatsSite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsSite(address string, alarmtemplateId string, countryCode string, createdTime float32, id string, lat float32, latlng LatLng, lng float32, modifiedTime float32, mspId string, name string, networktemplateId string, numAp int32, numApConnected int32, numClients int32, numDevices int32, numDevicesConnected int32, numGateway int32, numGatewayConnected int32, numSwitch int32, numSwitchConnected int32, orgId string, rftemplateId string, sitegroupIds []string, timezone string, tzoffset int32) *StatsSite {
	this := StatsSite{}
	this.Address = address
	this.AlarmtemplateId = alarmtemplateId
	this.CountryCode = countryCode
	this.CreatedTime = createdTime
	this.Id = id
	this.Lat = lat
	this.Latlng = latlng
	this.Lng = lng
	this.ModifiedTime = modifiedTime
	this.MspId = mspId
	this.Name = name
	this.NetworktemplateId = networktemplateId
	this.NumAp = numAp
	this.NumApConnected = numApConnected
	this.NumClients = numClients
	this.NumDevices = numDevices
	this.NumDevicesConnected = numDevicesConnected
	this.NumGateway = numGateway
	this.NumGatewayConnected = numGatewayConnected
	this.NumSwitch = numSwitch
	this.NumSwitchConnected = numSwitchConnected
	this.OrgId = orgId
	this.RftemplateId = rftemplateId
	this.SitegroupIds = sitegroupIds
	this.Timezone = timezone
	this.Tzoffset = tzoffset
	return &this
}

// NewStatsSiteWithDefaults instantiates a new StatsSite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsSiteWithDefaults() *StatsSite {
	this := StatsSite{}
	return &this
}

// GetAddress returns the Address field value
func (o *StatsSite) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *StatsSite) SetAddress(v string) {
	o.Address = v
}

// GetAlarmtemplateId returns the AlarmtemplateId field value
func (o *StatsSite) GetAlarmtemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AlarmtemplateId
}

// GetAlarmtemplateIdOk returns a tuple with the AlarmtemplateId field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetAlarmtemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlarmtemplateId, true
}

// SetAlarmtemplateId sets field value
func (o *StatsSite) SetAlarmtemplateId(v string) {
	o.AlarmtemplateId = v
}

// GetCountryCode returns the CountryCode field value
func (o *StatsSite) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *StatsSite) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *StatsSite) GetCreatedTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetCreatedTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *StatsSite) SetCreatedTime(v float32) {
	o.CreatedTime = v
}

// GetId returns the Id field value
func (o *StatsSite) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *StatsSite) SetId(v string) {
	o.Id = v
}

// GetLat returns the Lat field value
func (o *StatsSite) GetLat() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Lat
}

// GetLatOk returns a tuple with the Lat field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetLatOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lat, true
}

// SetLat sets field value
func (o *StatsSite) SetLat(v float32) {
	o.Lat = v
}

// GetLatlng returns the Latlng field value
func (o *StatsSite) GetLatlng() LatLng {
	if o == nil {
		var ret LatLng
		return ret
	}

	return o.Latlng
}

// GetLatlngOk returns a tuple with the Latlng field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetLatlngOk() (*LatLng, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latlng, true
}

// SetLatlng sets field value
func (o *StatsSite) SetLatlng(v LatLng) {
	o.Latlng = v
}

// GetLng returns the Lng field value
func (o *StatsSite) GetLng() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Lng
}

// GetLngOk returns a tuple with the Lng field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetLngOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lng, true
}

// SetLng sets field value
func (o *StatsSite) SetLng(v float32) {
	o.Lng = v
}

// GetModifiedTime returns the ModifiedTime field value
func (o *StatsSite) GetModifiedTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ModifiedTime
}

// GetModifiedTimeOk returns a tuple with the ModifiedTime field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetModifiedTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedTime, true
}

// SetModifiedTime sets field value
func (o *StatsSite) SetModifiedTime(v float32) {
	o.ModifiedTime = v
}

// GetMspId returns the MspId field value
func (o *StatsSite) GetMspId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MspId
}

// GetMspIdOk returns a tuple with the MspId field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetMspIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MspId, true
}

// SetMspId sets field value
func (o *StatsSite) SetMspId(v string) {
	o.MspId = v
}

// GetName returns the Name field value
func (o *StatsSite) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StatsSite) SetName(v string) {
	o.Name = v
}

// GetNetworktemplateId returns the NetworktemplateId field value
func (o *StatsSite) GetNetworktemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworktemplateId
}

// GetNetworktemplateIdOk returns a tuple with the NetworktemplateId field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNetworktemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworktemplateId, true
}

// SetNetworktemplateId sets field value
func (o *StatsSite) SetNetworktemplateId(v string) {
	o.NetworktemplateId = v
}

// GetNumAp returns the NumAp field value
func (o *StatsSite) GetNumAp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumAp
}

// GetNumApOk returns a tuple with the NumAp field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumApOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumAp, true
}

// SetNumAp sets field value
func (o *StatsSite) SetNumAp(v int32) {
	o.NumAp = v
}

// GetNumApConnected returns the NumApConnected field value
func (o *StatsSite) GetNumApConnected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumApConnected
}

// GetNumApConnectedOk returns a tuple with the NumApConnected field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumApConnectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumApConnected, true
}

// SetNumApConnected sets field value
func (o *StatsSite) SetNumApConnected(v int32) {
	o.NumApConnected = v
}

// GetNumClients returns the NumClients field value
func (o *StatsSite) GetNumClients() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumClients
}

// GetNumClientsOk returns a tuple with the NumClients field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumClientsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumClients, true
}

// SetNumClients sets field value
func (o *StatsSite) SetNumClients(v int32) {
	o.NumClients = v
}

// GetNumDevices returns the NumDevices field value
func (o *StatsSite) GetNumDevices() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumDevices
}

// GetNumDevicesOk returns a tuple with the NumDevices field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumDevicesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumDevices, true
}

// SetNumDevices sets field value
func (o *StatsSite) SetNumDevices(v int32) {
	o.NumDevices = v
}

// GetNumDevicesConnected returns the NumDevicesConnected field value
func (o *StatsSite) GetNumDevicesConnected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumDevicesConnected
}

// GetNumDevicesConnectedOk returns a tuple with the NumDevicesConnected field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumDevicesConnectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumDevicesConnected, true
}

// SetNumDevicesConnected sets field value
func (o *StatsSite) SetNumDevicesConnected(v int32) {
	o.NumDevicesConnected = v
}

// GetNumGateway returns the NumGateway field value
func (o *StatsSite) GetNumGateway() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumGateway
}

// GetNumGatewayOk returns a tuple with the NumGateway field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumGatewayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumGateway, true
}

// SetNumGateway sets field value
func (o *StatsSite) SetNumGateway(v int32) {
	o.NumGateway = v
}

// GetNumGatewayConnected returns the NumGatewayConnected field value
func (o *StatsSite) GetNumGatewayConnected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumGatewayConnected
}

// GetNumGatewayConnectedOk returns a tuple with the NumGatewayConnected field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumGatewayConnectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumGatewayConnected, true
}

// SetNumGatewayConnected sets field value
func (o *StatsSite) SetNumGatewayConnected(v int32) {
	o.NumGatewayConnected = v
}

// GetNumSwitch returns the NumSwitch field value
func (o *StatsSite) GetNumSwitch() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumSwitch
}

// GetNumSwitchOk returns a tuple with the NumSwitch field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumSwitchOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumSwitch, true
}

// SetNumSwitch sets field value
func (o *StatsSite) SetNumSwitch(v int32) {
	o.NumSwitch = v
}

// GetNumSwitchConnected returns the NumSwitchConnected field value
func (o *StatsSite) GetNumSwitchConnected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumSwitchConnected
}

// GetNumSwitchConnectedOk returns a tuple with the NumSwitchConnected field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetNumSwitchConnectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumSwitchConnected, true
}

// SetNumSwitchConnected sets field value
func (o *StatsSite) SetNumSwitchConnected(v int32) {
	o.NumSwitchConnected = v
}

// GetOrgId returns the OrgId field value
func (o *StatsSite) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *StatsSite) SetOrgId(v string) {
	o.OrgId = v
}

// GetRftemplateId returns the RftemplateId field value
func (o *StatsSite) GetRftemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RftemplateId
}

// GetRftemplateIdOk returns a tuple with the RftemplateId field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetRftemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RftemplateId, true
}

// SetRftemplateId sets field value
func (o *StatsSite) SetRftemplateId(v string) {
	o.RftemplateId = v
}

// GetSecpolicyId returns the SecpolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatsSite) GetSecpolicyId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SecpolicyId
}

// GetSecpolicyIdOk returns a tuple with the SecpolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatsSite) GetSecpolicyIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SecpolicyId) {
		return nil, false
	}
	return &o.SecpolicyId, true
}

// HasSecpolicyId returns a boolean if a field has been set.
func (o *StatsSite) HasSecpolicyId() bool {
	if o != nil && !IsNil(o.SecpolicyId) {
		return true
	}

	return false
}

// SetSecpolicyId gets a reference to the given interface{} and assigns it to the SecpolicyId field.
func (o *StatsSite) SetSecpolicyId(v interface{}) {
	o.SecpolicyId = v
}

// GetSitegroupIds returns the SitegroupIds field value
func (o *StatsSite) GetSitegroupIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SitegroupIds
}

// GetSitegroupIdsOk returns a tuple with the SitegroupIds field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetSitegroupIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitegroupIds, true
}

// SetSitegroupIds sets field value
func (o *StatsSite) SetSitegroupIds(v []string) {
	o.SitegroupIds = v
}

// GetTimezone returns the Timezone field value
func (o *StatsSite) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *StatsSite) SetTimezone(v string) {
	o.Timezone = v
}

// GetTzoffset returns the Tzoffset field value
func (o *StatsSite) GetTzoffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Tzoffset
}

// GetTzoffsetOk returns a tuple with the Tzoffset field value
// and a boolean to check if the value has been set.
func (o *StatsSite) GetTzoffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tzoffset, true
}

// SetTzoffset sets field value
func (o *StatsSite) SetTzoffset(v int32) {
	o.Tzoffset = v
}

func (o StatsSite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsSite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["alarmtemplate_id"] = o.AlarmtemplateId
	toSerialize["country_code"] = o.CountryCode
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["id"] = o.Id
	toSerialize["lat"] = o.Lat
	toSerialize["latlng"] = o.Latlng
	toSerialize["lng"] = o.Lng
	toSerialize["modified_time"] = o.ModifiedTime
	toSerialize["msp_id"] = o.MspId
	toSerialize["name"] = o.Name
	toSerialize["networktemplate_id"] = o.NetworktemplateId
	toSerialize["num_ap"] = o.NumAp
	toSerialize["num_ap_connected"] = o.NumApConnected
	toSerialize["num_clients"] = o.NumClients
	toSerialize["num_devices"] = o.NumDevices
	toSerialize["num_devices_connected"] = o.NumDevicesConnected
	toSerialize["num_gateway"] = o.NumGateway
	toSerialize["num_gateway_connected"] = o.NumGatewayConnected
	toSerialize["num_switch"] = o.NumSwitch
	toSerialize["num_switch_connected"] = o.NumSwitchConnected
	toSerialize["org_id"] = o.OrgId
	toSerialize["rftemplate_id"] = o.RftemplateId
	if o.SecpolicyId != nil {
		toSerialize["secpolicy_id"] = o.SecpolicyId
	}
	toSerialize["sitegroup_ids"] = o.SitegroupIds
	toSerialize["timezone"] = o.Timezone
	toSerialize["tzoffset"] = o.Tzoffset

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsSite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"alarmtemplate_id",
		"country_code",
		"created_time",
		"id",
		"lat",
		"latlng",
		"lng",
		"modified_time",
		"msp_id",
		"name",
		"networktemplate_id",
		"num_ap",
		"num_ap_connected",
		"num_clients",
		"num_devices",
		"num_devices_connected",
		"num_gateway",
		"num_gateway_connected",
		"num_switch",
		"num_switch_connected",
		"org_id",
		"rftemplate_id",
		"sitegroup_ids",
		"timezone",
		"tzoffset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsSite := _StatsSite{}

	err = json.Unmarshal(data, &varStatsSite)

	if err != nil {
		return err
	}

	*o = StatsSite(varStatsSite)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "alarmtemplate_id")
		delete(additionalProperties, "country_code")
		delete(additionalProperties, "created_time")
		delete(additionalProperties, "id")
		delete(additionalProperties, "lat")
		delete(additionalProperties, "latlng")
		delete(additionalProperties, "lng")
		delete(additionalProperties, "modified_time")
		delete(additionalProperties, "msp_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "networktemplate_id")
		delete(additionalProperties, "num_ap")
		delete(additionalProperties, "num_ap_connected")
		delete(additionalProperties, "num_clients")
		delete(additionalProperties, "num_devices")
		delete(additionalProperties, "num_devices_connected")
		delete(additionalProperties, "num_gateway")
		delete(additionalProperties, "num_gateway_connected")
		delete(additionalProperties, "num_switch")
		delete(additionalProperties, "num_switch_connected")
		delete(additionalProperties, "org_id")
		delete(additionalProperties, "rftemplate_id")
		delete(additionalProperties, "secpolicy_id")
		delete(additionalProperties, "sitegroup_ids")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "tzoffset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsSite struct {
	value *StatsSite
	isSet bool
}

func (v NullableStatsSite) Get() *StatsSite {
	return v.value
}

func (v *NullableStatsSite) Set(val *StatsSite) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsSite) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsSite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsSite(val *StatsSite) *NullableStatsSite {
	return &NullableStatsSite{value: val, isSet: true}
}

func (v NullableStatsSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsSite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


