/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// GatewayWanPpoeAuth if `type`==`pppoe`
type GatewayWanPpoeAuth string

// List of gateway_wan_ppoe_auth
const (
	GATEWAYWANPPOEAUTH_EMPTY GatewayWanPpoeAuth = ""
	GATEWAYWANPPOEAUTH_NONE GatewayWanPpoeAuth = "none"
	GATEWAYWANPPOEAUTH_CHAP GatewayWanPpoeAuth = "chap"
	GATEWAYWANPPOEAUTH_PAP GatewayWanPpoeAuth = "pap"
)

// All allowed values of GatewayWanPpoeAuth enum
var AllowedGatewayWanPpoeAuthEnumValues = []GatewayWanPpoeAuth{
	"",
	"none",
	"chap",
	"pap",
}

func (v *GatewayWanPpoeAuth) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GatewayWanPpoeAuth(value)
	for _, existing := range AllowedGatewayWanPpoeAuthEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GatewayWanPpoeAuth", value)
}

// NewGatewayWanPpoeAuthFromValue returns a pointer to a valid GatewayWanPpoeAuth
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGatewayWanPpoeAuthFromValue(v string) (*GatewayWanPpoeAuth, error) {
	ev := GatewayWanPpoeAuth(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GatewayWanPpoeAuth: valid values are %v", v, AllowedGatewayWanPpoeAuthEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GatewayWanPpoeAuth) IsValid() bool {
	for _, existing := range AllowedGatewayWanPpoeAuthEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to gateway_wan_ppoe_auth value
func (v GatewayWanPpoeAuth) Ptr() *GatewayWanPpoeAuth {
	return &v
}

type NullableGatewayWanPpoeAuth struct {
	value *GatewayWanPpoeAuth
	isSet bool
}

func (v NullableGatewayWanPpoeAuth) Get() *GatewayWanPpoeAuth {
	return v.value
}

func (v *NullableGatewayWanPpoeAuth) Set(val *GatewayWanPpoeAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayWanPpoeAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayWanPpoeAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayWanPpoeAuth(val *GatewayWanPpoeAuth) *NullableGatewayWanPpoeAuth {
	return &NullableGatewayWanPpoeAuth{value: val, isSet: true}
}

func (v NullableGatewayWanPpoeAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayWanPpoeAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

