/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// SiteSleImpactedApsScopeParameters the model 'SiteSleImpactedApsScopeParameters'
type SiteSleImpactedApsScopeParameters string

// List of site_sle_impacted_aps_scope_parameters
const (
	SITESLEIMPACTEDAPSSCOPEPARAMETERS_EMPTY SiteSleImpactedApsScopeParameters = ""
	SITESLEIMPACTEDAPSSCOPEPARAMETERS_SITE SiteSleImpactedApsScopeParameters = "site"
)

// All allowed values of SiteSleImpactedApsScopeParameters enum
var AllowedSiteSleImpactedApsScopeParametersEnumValues = []SiteSleImpactedApsScopeParameters{
	"",
	"site",
}

func (v *SiteSleImpactedApsScopeParameters) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SiteSleImpactedApsScopeParameters(value)
	for _, existing := range AllowedSiteSleImpactedApsScopeParametersEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SiteSleImpactedApsScopeParameters", value)
}

// NewSiteSleImpactedApsScopeParametersFromValue returns a pointer to a valid SiteSleImpactedApsScopeParameters
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSiteSleImpactedApsScopeParametersFromValue(v string) (*SiteSleImpactedApsScopeParameters, error) {
	ev := SiteSleImpactedApsScopeParameters(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SiteSleImpactedApsScopeParameters: valid values are %v", v, AllowedSiteSleImpactedApsScopeParametersEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SiteSleImpactedApsScopeParameters) IsValid() bool {
	for _, existing := range AllowedSiteSleImpactedApsScopeParametersEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to site_sle_impacted_aps_scope_parameters value
func (v SiteSleImpactedApsScopeParameters) Ptr() *SiteSleImpactedApsScopeParameters {
	return &v
}

type NullableSiteSleImpactedApsScopeParameters struct {
	value *SiteSleImpactedApsScopeParameters
	isSet bool
}

func (v NullableSiteSleImpactedApsScopeParameters) Get() *SiteSleImpactedApsScopeParameters {
	return v.value
}

func (v *NullableSiteSleImpactedApsScopeParameters) Set(val *SiteSleImpactedApsScopeParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteSleImpactedApsScopeParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteSleImpactedApsScopeParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteSleImpactedApsScopeParameters(val *SiteSleImpactedApsScopeParameters) *NullableSiteSleImpactedApsScopeParameters {
	return &NullableSiteSleImpactedApsScopeParameters{value: val, isSet: true}
}

func (v NullableSiteSleImpactedApsScopeParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteSleImpactedApsScopeParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

