/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// DiscoveredSwitchMetricType the model 'DiscoveredSwitchMetricType'
type DiscoveredSwitchMetricType string

// List of discovered_switch_metric_type
const (
	DISCOVEREDSWITCHMETRICTYPE_EMPTY DiscoveredSwitchMetricType = ""
	DISCOVEREDSWITCHMETRICTYPE_INACTIVE_WIRED_VLANS DiscoveredSwitchMetricType = "inactive_wired_vlans"
	DISCOVEREDSWITCHMETRICTYPE_SWITCH_AP_AFFINITY DiscoveredSwitchMetricType = "switch_ap_affinity"
	DISCOVEREDSWITCHMETRICTYPE_POE_COMPLIANCE DiscoveredSwitchMetricType = "poe_compliance"
	DISCOVEREDSWITCHMETRICTYPE_VERSION_COMPLIANCE DiscoveredSwitchMetricType = "version_compliance"
)

// All allowed values of DiscoveredSwitchMetricType enum
var AllowedDiscoveredSwitchMetricTypeEnumValues = []DiscoveredSwitchMetricType{
	"",
	"inactive_wired_vlans",
	"switch_ap_affinity",
	"poe_compliance",
	"version_compliance",
}

func (v *DiscoveredSwitchMetricType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiscoveredSwitchMetricType(value)
	for _, existing := range AllowedDiscoveredSwitchMetricTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiscoveredSwitchMetricType", value)
}

// NewDiscoveredSwitchMetricTypeFromValue returns a pointer to a valid DiscoveredSwitchMetricType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiscoveredSwitchMetricTypeFromValue(v string) (*DiscoveredSwitchMetricType, error) {
	ev := DiscoveredSwitchMetricType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiscoveredSwitchMetricType: valid values are %v", v, AllowedDiscoveredSwitchMetricTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiscoveredSwitchMetricType) IsValid() bool {
	for _, existing := range AllowedDiscoveredSwitchMetricTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to discovered_switch_metric_type value
func (v DiscoveredSwitchMetricType) Ptr() *DiscoveredSwitchMetricType {
	return &v
}

type NullableDiscoveredSwitchMetricType struct {
	value *DiscoveredSwitchMetricType
	isSet bool
}

func (v NullableDiscoveredSwitchMetricType) Get() *DiscoveredSwitchMetricType {
	return v.value
}

func (v *NullableDiscoveredSwitchMetricType) Set(val *DiscoveredSwitchMetricType) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveredSwitchMetricType) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveredSwitchMetricType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveredSwitchMetricType(val *DiscoveredSwitchMetricType) *NullableDiscoveredSwitchMetricType {
	return &NullableDiscoveredSwitchMetricType{value: val, isSet: true}
}

func (v NullableDiscoveredSwitchMetricType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveredSwitchMetricType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

