/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the ResponseSwitchMetricsConfigSuccessDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseSwitchMetricsConfigSuccessDetails{}

// ResponseSwitchMetricsConfigSuccessDetails struct for ResponseSwitchMetricsConfigSuccessDetails
type ResponseSwitchMetricsConfigSuccessDetails struct {
	ConfigSuccessCount *int32 `json:"config_success_count,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResponseSwitchMetricsConfigSuccessDetails ResponseSwitchMetricsConfigSuccessDetails

// NewResponseSwitchMetricsConfigSuccessDetails instantiates a new ResponseSwitchMetricsConfigSuccessDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseSwitchMetricsConfigSuccessDetails() *ResponseSwitchMetricsConfigSuccessDetails {
	this := ResponseSwitchMetricsConfigSuccessDetails{}
	return &this
}

// NewResponseSwitchMetricsConfigSuccessDetailsWithDefaults instantiates a new ResponseSwitchMetricsConfigSuccessDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseSwitchMetricsConfigSuccessDetailsWithDefaults() *ResponseSwitchMetricsConfigSuccessDetails {
	this := ResponseSwitchMetricsConfigSuccessDetails{}
	return &this
}

// GetConfigSuccessCount returns the ConfigSuccessCount field value if set, zero value otherwise.
func (o *ResponseSwitchMetricsConfigSuccessDetails) GetConfigSuccessCount() int32 {
	if o == nil || IsNil(o.ConfigSuccessCount) {
		var ret int32
		return ret
	}
	return *o.ConfigSuccessCount
}

// GetConfigSuccessCountOk returns a tuple with the ConfigSuccessCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSwitchMetricsConfigSuccessDetails) GetConfigSuccessCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ConfigSuccessCount) {
		return nil, false
	}
	return o.ConfigSuccessCount, true
}

// HasConfigSuccessCount returns a boolean if a field has been set.
func (o *ResponseSwitchMetricsConfigSuccessDetails) HasConfigSuccessCount() bool {
	if o != nil && !IsNil(o.ConfigSuccessCount) {
		return true
	}

	return false
}

// SetConfigSuccessCount gets a reference to the given int32 and assigns it to the ConfigSuccessCount field.
func (o *ResponseSwitchMetricsConfigSuccessDetails) SetConfigSuccessCount(v int32) {
	o.ConfigSuccessCount = &v
}

func (o ResponseSwitchMetricsConfigSuccessDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseSwitchMetricsConfigSuccessDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigSuccessCount) {
		toSerialize["config_success_count"] = o.ConfigSuccessCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResponseSwitchMetricsConfigSuccessDetails) UnmarshalJSON(data []byte) (err error) {
	varResponseSwitchMetricsConfigSuccessDetails := _ResponseSwitchMetricsConfigSuccessDetails{}

	err = json.Unmarshal(data, &varResponseSwitchMetricsConfigSuccessDetails)

	if err != nil {
		return err
	}

	*o = ResponseSwitchMetricsConfigSuccessDetails(varResponseSwitchMetricsConfigSuccessDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "config_success_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResponseSwitchMetricsConfigSuccessDetails struct {
	value *ResponseSwitchMetricsConfigSuccessDetails
	isSet bool
}

func (v NullableResponseSwitchMetricsConfigSuccessDetails) Get() *ResponseSwitchMetricsConfigSuccessDetails {
	return v.value
}

func (v *NullableResponseSwitchMetricsConfigSuccessDetails) Set(val *ResponseSwitchMetricsConfigSuccessDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseSwitchMetricsConfigSuccessDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseSwitchMetricsConfigSuccessDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseSwitchMetricsConfigSuccessDetails(val *ResponseSwitchMetricsConfigSuccessDetails) *NullableResponseSwitchMetricsConfigSuccessDetails {
	return &NullableResponseSwitchMetricsConfigSuccessDetails{value: val, isSet: true}
}

func (v NullableResponseSwitchMetricsConfigSuccessDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseSwitchMetricsConfigSuccessDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


