/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// VirtualChassisPortOperation the model 'VirtualChassisPortOperation'
type VirtualChassisPortOperation string

// List of virtual_chassis_port_operation
const (
	VIRTUALCHASSISPORTOPERATION_EMPTY VirtualChassisPortOperation = ""
	VIRTUALCHASSISPORTOPERATION_SET VirtualChassisPortOperation = "set"
	VIRTUALCHASSISPORTOPERATION_DELETE VirtualChassisPortOperation = "delete"
)

// All allowed values of VirtualChassisPortOperation enum
var AllowedVirtualChassisPortOperationEnumValues = []VirtualChassisPortOperation{
	"",
	"set",
	"delete",
}

func (v *VirtualChassisPortOperation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VirtualChassisPortOperation(value)
	for _, existing := range AllowedVirtualChassisPortOperationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VirtualChassisPortOperation", value)
}

// NewVirtualChassisPortOperationFromValue returns a pointer to a valid VirtualChassisPortOperation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVirtualChassisPortOperationFromValue(v string) (*VirtualChassisPortOperation, error) {
	ev := VirtualChassisPortOperation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VirtualChassisPortOperation: valid values are %v", v, AllowedVirtualChassisPortOperationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VirtualChassisPortOperation) IsValid() bool {
	for _, existing := range AllowedVirtualChassisPortOperationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to virtual_chassis_port_operation value
func (v VirtualChassisPortOperation) Ptr() *VirtualChassisPortOperation {
	return &v
}

type NullableVirtualChassisPortOperation struct {
	value *VirtualChassisPortOperation
	isSet bool
}

func (v NullableVirtualChassisPortOperation) Get() *VirtualChassisPortOperation {
	return v.value
}

func (v *NullableVirtualChassisPortOperation) Set(val *VirtualChassisPortOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualChassisPortOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualChassisPortOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualChassisPortOperation(val *VirtualChassisPortOperation) *NullableVirtualChassisPortOperation {
	return &NullableVirtualChassisPortOperation{value: val, isSet: true}
}

func (v NullableVirtualChassisPortOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualChassisPortOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

