/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// SearchSiteDevicesDescSort the model 'SearchSiteDevicesDescSort'
type SearchSiteDevicesDescSort string

// List of search_site_devices_desc_sort
const (
	SEARCHSITEDEVICESDESCSORT_EMPTY SearchSiteDevicesDescSort = ""
	SEARCHSITEDEVICESDESCSORT_TIMESTAMP SearchSiteDevicesDescSort = "timestamp"
	SEARCHSITEDEVICESDESCSORT_MAC SearchSiteDevicesDescSort = "mac"
	SEARCHSITEDEVICESDESCSORT_MODEL SearchSiteDevicesDescSort = "model"
	SEARCHSITEDEVICESDESCSORT_SKU SearchSiteDevicesDescSort = "sku"
)

// All allowed values of SearchSiteDevicesDescSort enum
var AllowedSearchSiteDevicesDescSortEnumValues = []SearchSiteDevicesDescSort{
	"",
	"timestamp",
	"mac",
	"model",
	"sku",
}

func (v *SearchSiteDevicesDescSort) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SearchSiteDevicesDescSort(value)
	for _, existing := range AllowedSearchSiteDevicesDescSortEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SearchSiteDevicesDescSort", value)
}

// NewSearchSiteDevicesDescSortFromValue returns a pointer to a valid SearchSiteDevicesDescSort
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSearchSiteDevicesDescSortFromValue(v string) (*SearchSiteDevicesDescSort, error) {
	ev := SearchSiteDevicesDescSort(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SearchSiteDevicesDescSort: valid values are %v", v, AllowedSearchSiteDevicesDescSortEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SearchSiteDevicesDescSort) IsValid() bool {
	for _, existing := range AllowedSearchSiteDevicesDescSortEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to search_site_devices_desc_sort value
func (v SearchSiteDevicesDescSort) Ptr() *SearchSiteDevicesDescSort {
	return &v
}

type NullableSearchSiteDevicesDescSort struct {
	value *SearchSiteDevicesDescSort
	isSet bool
}

func (v NullableSearchSiteDevicesDescSort) Get() *SearchSiteDevicesDescSort {
	return v.value
}

func (v *NullableSearchSiteDevicesDescSort) Set(val *SearchSiteDevicesDescSort) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSiteDevicesDescSort) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSiteDevicesDescSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSiteDevicesDescSort(val *SearchSiteDevicesDescSort) *NullableSearchSiteDevicesDescSort {
	return &NullableSearchSiteDevicesDescSort{value: val, isSet: true}
}

func (v NullableSearchSiteDevicesDescSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSiteDevicesDescSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

