/*
Mist API

> Version: **2406.1.14** > > Date: **July 3, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.14
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the MapOrgImportFileJson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapOrgImportFileJson{}

// MapOrgImportFileJson struct for MapOrgImportFileJson
type MapOrgImportFileJson struct {
	ImportAllFloorplans *bool `json:"import_all_floorplans,omitempty"`
	ImportHeight *bool `json:"import_height,omitempty"`
	ImportOrientation *bool `json:"import_orientation,omitempty"`
	SiteId *string `json:"site_id,omitempty"`
	VendorName MapOrgImportFileJsonVendorName `json:"vendor_name"`
	AdditionalProperties map[string]interface{}
}

type _MapOrgImportFileJson MapOrgImportFileJson

// NewMapOrgImportFileJson instantiates a new MapOrgImportFileJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapOrgImportFileJson(vendorName MapOrgImportFileJsonVendorName) *MapOrgImportFileJson {
	this := MapOrgImportFileJson{}
	var importAllFloorplans bool = false
	this.ImportAllFloorplans = &importAllFloorplans
	var importHeight bool = true
	this.ImportHeight = &importHeight
	var importOrientation bool = true
	this.ImportOrientation = &importOrientation
	this.VendorName = vendorName
	return &this
}

// NewMapOrgImportFileJsonWithDefaults instantiates a new MapOrgImportFileJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapOrgImportFileJsonWithDefaults() *MapOrgImportFileJson {
	this := MapOrgImportFileJson{}
	var importAllFloorplans bool = false
	this.ImportAllFloorplans = &importAllFloorplans
	var importHeight bool = true
	this.ImportHeight = &importHeight
	var importOrientation bool = true
	this.ImportOrientation = &importOrientation
	return &this
}

// GetImportAllFloorplans returns the ImportAllFloorplans field value if set, zero value otherwise.
func (o *MapOrgImportFileJson) GetImportAllFloorplans() bool {
	if o == nil || IsNil(o.ImportAllFloorplans) {
		var ret bool
		return ret
	}
	return *o.ImportAllFloorplans
}

// GetImportAllFloorplansOk returns a tuple with the ImportAllFloorplans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapOrgImportFileJson) GetImportAllFloorplansOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportAllFloorplans) {
		return nil, false
	}
	return o.ImportAllFloorplans, true
}

// HasImportAllFloorplans returns a boolean if a field has been set.
func (o *MapOrgImportFileJson) HasImportAllFloorplans() bool {
	if o != nil && !IsNil(o.ImportAllFloorplans) {
		return true
	}

	return false
}

// SetImportAllFloorplans gets a reference to the given bool and assigns it to the ImportAllFloorplans field.
func (o *MapOrgImportFileJson) SetImportAllFloorplans(v bool) {
	o.ImportAllFloorplans = &v
}

// GetImportHeight returns the ImportHeight field value if set, zero value otherwise.
func (o *MapOrgImportFileJson) GetImportHeight() bool {
	if o == nil || IsNil(o.ImportHeight) {
		var ret bool
		return ret
	}
	return *o.ImportHeight
}

// GetImportHeightOk returns a tuple with the ImportHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapOrgImportFileJson) GetImportHeightOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportHeight) {
		return nil, false
	}
	return o.ImportHeight, true
}

// HasImportHeight returns a boolean if a field has been set.
func (o *MapOrgImportFileJson) HasImportHeight() bool {
	if o != nil && !IsNil(o.ImportHeight) {
		return true
	}

	return false
}

// SetImportHeight gets a reference to the given bool and assigns it to the ImportHeight field.
func (o *MapOrgImportFileJson) SetImportHeight(v bool) {
	o.ImportHeight = &v
}

// GetImportOrientation returns the ImportOrientation field value if set, zero value otherwise.
func (o *MapOrgImportFileJson) GetImportOrientation() bool {
	if o == nil || IsNil(o.ImportOrientation) {
		var ret bool
		return ret
	}
	return *o.ImportOrientation
}

// GetImportOrientationOk returns a tuple with the ImportOrientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapOrgImportFileJson) GetImportOrientationOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportOrientation) {
		return nil, false
	}
	return o.ImportOrientation, true
}

// HasImportOrientation returns a boolean if a field has been set.
func (o *MapOrgImportFileJson) HasImportOrientation() bool {
	if o != nil && !IsNil(o.ImportOrientation) {
		return true
	}

	return false
}

// SetImportOrientation gets a reference to the given bool and assigns it to the ImportOrientation field.
func (o *MapOrgImportFileJson) SetImportOrientation(v bool) {
	o.ImportOrientation = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *MapOrgImportFileJson) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapOrgImportFileJson) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *MapOrgImportFileJson) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *MapOrgImportFileJson) SetSiteId(v string) {
	o.SiteId = &v
}

// GetVendorName returns the VendorName field value
func (o *MapOrgImportFileJson) GetVendorName() MapOrgImportFileJsonVendorName {
	if o == nil {
		var ret MapOrgImportFileJsonVendorName
		return ret
	}

	return o.VendorName
}

// GetVendorNameOk returns a tuple with the VendorName field value
// and a boolean to check if the value has been set.
func (o *MapOrgImportFileJson) GetVendorNameOk() (*MapOrgImportFileJsonVendorName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VendorName, true
}

// SetVendorName sets field value
func (o *MapOrgImportFileJson) SetVendorName(v MapOrgImportFileJsonVendorName) {
	o.VendorName = v
}

func (o MapOrgImportFileJson) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapOrgImportFileJson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImportAllFloorplans) {
		toSerialize["import_all_floorplans"] = o.ImportAllFloorplans
	}
	if !IsNil(o.ImportHeight) {
		toSerialize["import_height"] = o.ImportHeight
	}
	if !IsNil(o.ImportOrientation) {
		toSerialize["import_orientation"] = o.ImportOrientation
	}
	if !IsNil(o.SiteId) {
		toSerialize["site_id"] = o.SiteId
	}
	toSerialize["vendor_name"] = o.VendorName

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MapOrgImportFileJson) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vendor_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMapOrgImportFileJson := _MapOrgImportFileJson{}

	err = json.Unmarshal(data, &varMapOrgImportFileJson)

	if err != nil {
		return err
	}

	*o = MapOrgImportFileJson(varMapOrgImportFileJson)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "import_all_floorplans")
		delete(additionalProperties, "import_height")
		delete(additionalProperties, "import_orientation")
		delete(additionalProperties, "site_id")
		delete(additionalProperties, "vendor_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMapOrgImportFileJson struct {
	value *MapOrgImportFileJson
	isSet bool
}

func (v NullableMapOrgImportFileJson) Get() *MapOrgImportFileJson {
	return v.value
}

func (v *NullableMapOrgImportFileJson) Set(val *MapOrgImportFileJson) {
	v.value = val
	v.isSet = true
}

func (v NullableMapOrgImportFileJson) IsSet() bool {
	return v.isSet
}

func (v *NullableMapOrgImportFileJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapOrgImportFileJson(val *MapOrgImportFileJson) *NullableMapOrgImportFileJson {
	return &NullableMapOrgImportFileJson{value: val, isSet: true}
}

func (v NullableMapOrgImportFileJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapOrgImportFileJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


