/*
Mist API

Testing OrgsWLANTemplatesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistsdkgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tmunzer/mistsdkgo"
)

func Test_mistsdkgo_OrgsWLANTemplatesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrgsWLANTemplatesAPIService CloneOrgTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var templateId string

		resp, httpRes, err := apiClient.OrgsWLANTemplatesAPI.CloneOrgTemplate(context.Background(), orgId, templateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsWLANTemplatesAPIService CreateOrgTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.OrgsWLANTemplatesAPI.CreateOrgTemplate(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsWLANTemplatesAPIService DeleteOrgTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var templateId string

		httpRes, err := apiClient.OrgsWLANTemplatesAPI.DeleteOrgTemplate(context.Background(), orgId, templateId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsWLANTemplatesAPIService GetOrgTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var templateId string

		resp, httpRes, err := apiClient.OrgsWLANTemplatesAPI.GetOrgTemplate(context.Background(), orgId, templateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsWLANTemplatesAPIService ListOrgTemplates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.OrgsWLANTemplatesAPI.ListOrgTemplates(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsWLANTemplatesAPIService UpdateOrgTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var templateId string

		resp, httpRes, err := apiClient.OrgsWLANTemplatesAPI.UpdateOrgTemplate(context.Background(), orgId, templateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
