/*
Mist API

Testing OrgsSiteTemplatesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistsdkgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tmunzer/mistsdkgo"
)

func Test_mistsdkgo_OrgsSiteTemplatesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrgsSiteTemplatesAPIService CreateOrgSiteTemplates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.OrgsSiteTemplatesAPI.CreateOrgSiteTemplates(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsSiteTemplatesAPIService DeleteOrgSiteTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var sitetemplateId string

		httpRes, err := apiClient.OrgsSiteTemplatesAPI.DeleteOrgSiteTemplate(context.Background(), orgId, sitetemplateId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsSiteTemplatesAPIService GetOrgSiteTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var sitetemplateId string

		resp, httpRes, err := apiClient.OrgsSiteTemplatesAPI.GetOrgSiteTemplate(context.Background(), orgId, sitetemplateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsSiteTemplatesAPIService ListOrgSiteTemplates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.OrgsSiteTemplatesAPI.ListOrgSiteTemplates(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrgsSiteTemplatesAPIService UpdateOrgSiteTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var sitetemplateId string

		resp, httpRes, err := apiClient.OrgsSiteTemplatesAPI.UpdateOrgSiteTemplate(context.Background(), orgId, sitetemplateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
